name: Build and test CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java-version: [ 11 ]
        java-distribution: [ 'adopt' ]
    if:
      contains('refs/heads/main', github.ref)
    steps:
    - uses: actions/checkout@v2
        name: Use test for java ${{ matrix.java-version }}
    - uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.java-distribution }}
        java-version: ${{ matrix.java-version }}
        check-latest: true
    - run: |
          touch src/main/resources/application.properties
          echo ${{ secrets.CATMASH_DB_TEST }} >> src/main/resources/application.properties
    - run: ./mvnw clean verify

  # deploy:
  #   name: Deployment
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   if:
  #     contains('
  #       refs/heads/dev
  #       refs/heads/staging
  #       refs/heads/production
  #     ', github.ref)
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use test for java ${{ matrix.java-version }}
  #   - uses: actions/setup-java@v2
